/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggregateFamily {
    /// * `4` - IPv4 * `6` - IPv6
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl AggregateFamily {
    pub fn new() -> AggregateFamily {
        AggregateFamily {
            value: None,
            label: None,
        }
    }
}

/// * `4` - IPv4 * `6` - IPv6
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "6")]
    Variant6,
}

impl Default for Value {
    fn default() -> Value {
        Self::Variant4
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "IPv4")]
    Ipv4,
    #[serde(rename = "IPv6")]
    Ipv6,
}

impl Default for Label {
    fn default() -> Label {
        Self::Ipv4
    }
}

