/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AvailableVlan : Representation of a VLAN which does not exist in the database.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailableVlan {
    #[serde(rename = "vid")]
    pub vid: i32,
    #[serde(rename = "group")]
    pub group: Box<crate::models::NestedVlanGroup>,
}

impl AvailableVlan {
    /// Representation of a VLAN which does not exist in the database.
    pub fn new(vid: i32, group: crate::models::NestedVlanGroup) -> AvailableVlan {
        AvailableVlan {
            vid,
            group: Box::new(group),
        }
    }
}


