/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CableTerminationRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CableTerminationRequest {
    #[serde(rename = "cable")]
    pub cable: i32,
    /// * `A` - A * `B` - B
    #[serde(rename = "cable_end")]
    pub cable_end: CableEnd,
    #[serde(rename = "termination_type")]
    pub termination_type: String,
    #[serde(rename = "termination_id")]
    pub termination_id: i64,
}

impl CableTerminationRequest {
    /// Adds support for custom fields and tags.
    pub fn new(cable: i32, cable_end: CableEnd, termination_type: String, termination_id: i64) -> CableTerminationRequest {
        CableTerminationRequest {
            cable,
            cable_end,
            termination_type,
            termination_id,
        }
    }
}

/// * `A` - A * `B` - B
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CableEnd {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "B")]
    B,
}

impl Default for CableEnd {
    fn default() -> CableEnd {
        Self::A
    }
}

