/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ComponentNestedModuleRequest : Used by device component serializers.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentNestedModuleRequest {
    #[serde(rename = "device")]
    pub device: i32,
}

impl ComponentNestedModuleRequest {
    /// Used by device component serializers.
    pub fn new(device: i32) -> ComponentNestedModuleRequest {
        ComponentNestedModuleRequest {
            device,
        }
    }
}


