/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentType {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "app_label")]
    pub app_label: String,
    #[serde(rename = "model")]
    pub model: String,
}

impl ContentType {
    pub fn new(id: i32, url: String, display: String, app_label: String, model: String) -> ContentType {
        ContentType {
            id,
            url,
            display,
            app_label,
            model,
        }
    }
}


