/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContactAssignment : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContactAssignment {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "object_id")]
    pub object_id: i64,
    #[serde(rename = "object")]
    pub object: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "contact")]
    pub contact: Box<crate::models::NestedContact>,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<Box<crate::models::NestedContactRole>>>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Box<crate::models::ContactAssignmentPriority>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl ContactAssignment {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, content_type: String, object_id: i64, object: ::std::collections::HashMap<String, serde_json::Value>, contact: crate::models::NestedContact, created: Option<String>, last_updated: Option<String>) -> ContactAssignment {
        ContactAssignment {
            id,
            url,
            display,
            content_type,
            object_id,
            object,
            contact: Box::new(contact),
            role: None,
            priority: None,
            tags: None,
            created,
            last_updated,
        }
    }
}


