/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CustomField : Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomField {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "content_types")]
    pub content_types: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::CustomFieldType>,
    #[serde(rename = "object_type", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
    #[serde(rename = "data_type")]
    pub data_type: String,
    /// Internal field name
    #[serde(rename = "name")]
    pub name: String,
    /// Name of the field as displayed to users (if not provided, 'the field's name will be used)
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Custom fields within the same group will be displayed together
    #[serde(rename = "group_name", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// If true, this field is required when creating new objects or editing an existing object.
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    /// Weighting for search. Lower values are considered more important. Fields with a search weight of zero will be ignored.
    #[serde(rename = "search_weight", skip_serializing_if = "Option::is_none")]
    pub search_weight: Option<i32>,
    #[serde(rename = "filter_logic", skip_serializing_if = "Option::is_none")]
    pub filter_logic: Option<Box<crate::models::CustomFieldFilterLogic>>,
    #[serde(rename = "ui_visibility", skip_serializing_if = "Option::is_none")]
    pub ui_visibility: Option<Box<crate::models::CustomFieldUiVisibility>>,
    /// Replicate this value when cloning objects
    #[serde(rename = "is_cloneable", skip_serializing_if = "Option::is_none")]
    pub is_cloneable: Option<bool>,
    /// Default value for the field (must be a JSON value). Encapsulate strings with double quotes (e.g. \"Foo\").
    #[serde(rename = "default", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default: Option<Option<::std::collections::HashMap<String, serde_json::Value>>>,
    /// Fields with higher weights appear lower in a form.
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    /// Minimum allowed value (for numeric fields)
    #[serde(rename = "validation_minimum", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub validation_minimum: Option<Option<i32>>,
    /// Maximum allowed value (for numeric fields)
    #[serde(rename = "validation_maximum", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub validation_maximum: Option<Option<i32>>,
    /// Regular expression to enforce on text field values. Use ^ and $ to force matching of entire string. For example, <code>^[A-Z]{3}$</code> will limit values to exactly three uppercase letters.
    #[serde(rename = "validation_regex", skip_serializing_if = "Option::is_none")]
    pub validation_regex: Option<String>,
    #[serde(rename = "choice_set", skip_serializing_if = "Option::is_none")]
    pub choice_set: Option<Box<crate::models::NestedCustomFieldChoiceSet>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl CustomField {
    /// Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)
    pub fn new(id: i32, url: String, display: String, content_types: Vec<String>, r#type: crate::models::CustomFieldType, data_type: String, name: String, created: Option<String>, last_updated: Option<String>) -> CustomField {
        CustomField {
            id,
            url,
            display,
            content_types,
            r#type: Box::new(r#type),
            object_type: None,
            data_type,
            name,
            label: None,
            group_name: None,
            description: None,
            required: None,
            search_weight: None,
            filter_logic: None,
            ui_visibility: None,
            is_cloneable: None,
            default: None,
            weight: None,
            validation_minimum: None,
            validation_maximum: None,
            validation_regex: None,
            choice_set: None,
            created,
            last_updated,
        }
    }
}


