/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardRequest {
    #[serde(rename = "layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl DashboardRequest {
    pub fn new() -> DashboardRequest {
        DashboardRequest {
            layout: None,
            config: None,
        }
    }
}


