/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DataFile : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataFile {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "source")]
    pub source: Box<crate::models::NestedDataSource>,
    /// File path relative to the data source's root
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "last_updated")]
    pub last_updated: String,
    #[serde(rename = "size")]
    pub size: i32,
    /// SHA256 hash of the file data
    #[serde(rename = "hash")]
    pub hash: String,
}

impl DataFile {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, source: crate::models::NestedDataSource, path: String, last_updated: String, size: i32, hash: String) -> DataFile {
        DataFile {
            id,
            url,
            display,
            source: Box::new(source),
            path,
            last_updated,
            size,
            hash,
        }
    }
}


