/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeviceRole : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceRole {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Virtual machines may be assigned to this role
    #[serde(rename = "vm_role", skip_serializing_if = "Option::is_none")]
    pub vm_role: Option<bool>,
    #[serde(rename = "config_template", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config_template: Option<Option<Box<crate::models::NestedConfigTemplate>>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTag>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
    #[serde(rename = "device_count")]
    pub device_count: i32,
    #[serde(rename = "virtualmachine_count")]
    pub virtualmachine_count: i32,
}

impl DeviceRole {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, name: String, slug: String, created: Option<String>, last_updated: Option<String>, device_count: i32, virtualmachine_count: i32) -> DeviceRole {
        DeviceRole {
            id,
            url,
            display,
            name,
            slug,
            color: None,
            vm_role: None,
            config_template: None,
            description: None,
            tags: None,
            custom_fields: None,
            created,
            last_updated,
            device_count,
            virtualmachine_count,
        }
    }
}


