/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceTypeSubdeviceRole {
    /// * `parent` - Parent * `child` - Child
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl DeviceTypeSubdeviceRole {
    pub fn new() -> DeviceTypeSubdeviceRole {
        DeviceTypeSubdeviceRole {
            value: None,
            label: None,
        }
    }
}

/// * `parent` - Parent * `child` - Child
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "parent")]
    Parent,
    #[serde(rename = "child")]
    Child,
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "null")]
    Null,
}

impl Default for Value {
    fn default() -> Value {
        Self::Parent
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Parent")]
    Parent,
    #[serde(rename = "Child")]
    Child,
}

impl Default for Label {
    fn default() -> Label {
        Self::Parent
    }
}

