/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FhrpGroupAssignment : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FhrpGroupAssignment {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "display")]
    pub display: String,
    #[serde(rename = "group")]
    pub group: Box<crate::models::NestedFhrpGroup>,
    #[serde(rename = "interface_type")]
    pub interface_type: String,
    #[serde(rename = "interface_id")]
    pub interface_id: i64,
    #[serde(rename = "interface", deserialize_with = "Option::deserialize")]
    pub interface: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "created", deserialize_with = "Option::deserialize")]
    pub created: Option<String>,
    #[serde(rename = "last_updated", deserialize_with = "Option::deserialize")]
    pub last_updated: Option<String>,
}

impl FhrpGroupAssignment {
    /// Adds support for custom fields and tags.
    pub fn new(id: i32, url: String, display: String, group: crate::models::NestedFhrpGroup, interface_type: String, interface_id: i64, interface: Option<::std::collections::HashMap<String, serde_json::Value>>, priority: i32, created: Option<String>, last_updated: Option<String>) -> FhrpGroupAssignment {
        FhrpGroupAssignment {
            id,
            url,
            display,
            group: Box::new(group),
            interface_type,
            interface_id,
            interface,
            priority,
            created,
            last_updated,
        }
    }
}


