/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FrontPortRearPortRequest : NestedRearPortSerializer but with parent device omitted (since front and rear ports must belong to same device)



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrontPortRearPortRequest {
    #[serde(rename = "name")]
    pub name: String,
    /// Physical label
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl FrontPortRearPortRequest {
    /// NestedRearPortSerializer but with parent device omitted (since front and rear ports must belong to same device)
    pub fn new(name: String) -> FrontPortRearPortRequest {
        FrontPortRearPortRequest {
            name,
            label: None,
            description: None,
        }
    }
}


