/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterfaceMode {
    /// * `access` - Access * `tagged` - Tagged * `tagged-all` - Tagged (All)
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl InterfaceMode {
    pub fn new() -> InterfaceMode {
        InterfaceMode {
            value: None,
            label: None,
        }
    }
}

/// * `access` - Access * `tagged` - Tagged * `tagged-all` - Tagged (All)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "tagged")]
    Tagged,
    #[serde(rename = "tagged-all")]
    TaggedAll,
    #[serde(rename = "")]
    Empty,
}

impl Default for Value {
    fn default() -> Value {
        Self::Access
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Access")]
    Access,
    #[serde(rename = "Tagged")]
    Tagged,
    #[serde(rename = "Tagged (All)")]
    TaggedLeftParenthesisAllRightParenthesis,
}

impl Default for Label {
    fn default() -> Label {
        Self::Access
    }
}

