/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// L2VpnTerminationRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct L2VpnTerminationRequest {
    #[serde(rename = "l2vpn")]
    pub l2vpn: Box<crate::models::NestedL2VpnRequest>,
    #[serde(rename = "assigned_object_type")]
    pub assigned_object_type: String,
    #[serde(rename = "assigned_object_id")]
    pub assigned_object_id: i64,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl L2VpnTerminationRequest {
    /// Adds support for custom fields and tags.
    pub fn new(l2vpn: crate::models::NestedL2VpnRequest, assigned_object_type: String, assigned_object_id: i64) -> L2VpnTerminationRequest {
        L2VpnTerminationRequest {
            l2vpn: Box::new(l2vpn),
            assigned_object_type,
            assigned_object_id,
            tags: None,
            custom_fields: None,
        }
    }
}


