/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchedCableTerminationRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedCableTerminationRequest {
    #[serde(rename = "cable", skip_serializing_if = "Option::is_none")]
    pub cable: Option<i32>,
    /// * `A` - A * `B` - B
    #[serde(rename = "cable_end", skip_serializing_if = "Option::is_none")]
    pub cable_end: Option<CableEnd>,
    #[serde(rename = "termination_type", skip_serializing_if = "Option::is_none")]
    pub termination_type: Option<String>,
    #[serde(rename = "termination_id", skip_serializing_if = "Option::is_none")]
    pub termination_id: Option<i64>,
}

impl PatchedCableTerminationRequest {
    /// Adds support for custom fields and tags.
    pub fn new() -> PatchedCableTerminationRequest {
        PatchedCableTerminationRequest {
            cable: None,
            cable_end: None,
            termination_type: None,
            termination_id: None,
        }
    }
}

/// * `A` - A * `B` - B
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CableEnd {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "B")]
    B,
}

impl Default for CableEnd {
    fn default() -> CableEnd {
        Self::A
    }
}

