/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchedWritableConfigTemplateRequest : Introduces support for Tag assignment. Adds `tags` serialization, and handles tag assignment on create() and update().



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedWritableConfigTemplateRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Any <a href=\"https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment\">additional parameters</a> to pass when constructing the Jinja2 environment.
    #[serde(rename = "environment_params", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub environment_params: Option<Option<::std::collections::HashMap<String, serde_json::Value>>>,
    /// Jinja2 template code.
    #[serde(rename = "template_code", skip_serializing_if = "Option::is_none")]
    pub template_code: Option<String>,
    /// Remote data source
    #[serde(rename = "data_source", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_source: Option<Option<i32>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
}

impl PatchedWritableConfigTemplateRequest {
    /// Introduces support for Tag assignment. Adds `tags` serialization, and handles tag assignment on create() and update().
    pub fn new() -> PatchedWritableConfigTemplateRequest {
        PatchedWritableConfigTemplateRequest {
            name: None,
            description: None,
            environment_params: None,
            template_code: None,
            data_source: None,
            tags: None,
        }
    }
}


