/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VirtualDeviceContextStatus {
    /// * `active` - Active * `planned` - Planned * `offline` - Offline
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<Label>,
}

impl VirtualDeviceContextStatus {
    pub fn new() -> VirtualDeviceContextStatus {
        VirtualDeviceContextStatus {
            value: None,
            label: None,
        }
    }
}

/// * `active` - Active * `planned` - Planned * `offline` - Offline
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "planned")]
    Planned,
    #[serde(rename = "offline")]
    Offline,
}

impl Default for Value {
    fn default() -> Value {
        Self::Active
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Planned")]
    Planned,
    #[serde(rename = "Offline")]
    Offline,
}

impl Default for Label {
    fn default() -> Label {
        Self::Active
    }
}

