/*
 * NetBox REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.6.0 (3.6)
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WritableContactAssignmentRequest : Adds support for custom fields and tags.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WritableContactAssignmentRequest {
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "object_id")]
    pub object_id: i64,
    #[serde(rename = "contact")]
    pub contact: i32,
    #[serde(rename = "role")]
    pub role: i32,
    /// * `primary` - Primary * `secondary` - Secondary * `tertiary` - Tertiary * `inactive` - Inactive
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<crate::models::NestedTagRequest>>,
}

impl WritableContactAssignmentRequest {
    /// Adds support for custom fields and tags.
    pub fn new(content_type: String, object_id: i64, contact: i32, role: i32) -> WritableContactAssignmentRequest {
        WritableContactAssignmentRequest {
            content_type,
            object_id,
            contact,
            role,
            priority: None,
            tags: None,
        }
    }
}

/// * `primary` - Primary * `secondary` - Secondary * `tertiary` - Tertiary * `inactive` - Inactive
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "secondary")]
    Secondary,
    #[serde(rename = "tertiary")]
    Tertiary,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "")]
    Empty,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::Primary
    }
}

